### ISSUE TITLE
Translate to other languages

### ISSUE THREAD

**Issue by brylie** [GeriLife/coronavirus_mapper#3]
Translate the following phrases to various languages:

- Coronavirus symptoms
- Add report
- Submit report
- First symptomatic
- Location
- Close
- Submit

Translators: please add your translations below as comments on this issue.

**Comment by marreapato** [comment]
Portuguese(BR)

* Sintomas de Coronavírus
* Adicionar relatório
* Enviar relatório
* Primeiro Sintomático
* Local
* Fechar
* Enviar

**Comment by Joerockafella** [comment]
French (FR)

- Symptômes du coronavirus
- Ajouter un rapport
- Soumettre un rapport
- Premier symptôme
- Lieu
- Fermer
- Soumettre

**Comment by brylie** [comment]
Thank you @Joerockafella :-)

**Comment by brylie** [comment]
@all-contributors please add @marreapato for translation

**Comment by brylie** [comment]
@all-contributors please add @marreapato for translation

**Comment by brylie** [comment]
@all-contributors please add @Joerockafella for translation

**Comment by brylie** [comment]
Thank you very much for your contributions @marreapato and @Joerockafella :-)
